# todo: добавить контейнер postgres
services:
  postgres:
    image: postgres:14.10-alpine
    container_name: personal_account_api
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data  

volumes:
  pgdata:

# скачать pgAdmin

# Запустить
# docker compose build
# docker compose up

# Остановить
# docker compose down

# docker compose up --build