app:
  name: "PersonalAccountApi"
  port: "8080"
  workers:
    number: 10
    queue_len: 1000
  cache:
    ttl: 60
    interval: 10
  debug: true

db:
  host: "postgres"
  port: 5432
  user: "postgres"
  pass: "postgres"
  name: "postgres"

storage:
  path: "/app/uploads"

metrics:
  port: "9091"