app:
  name: "PersonalAccountApi"
  port: "8080"
  workers_number: 10
  cache:
    ttl: 5
    interval: 10
  debug: true

db:
  host: "postgres"
  port: 5432
  user: "postgres"
  pass: "postgres"
  name: "postgres"

storage:
  path: "/app/uploads"

metrics:
  port: "9091"