app:
  name: "PersonalAccountApi"
  port: "8080"
  debug: true

DB:
  host: "postgres"
  port: 5432
  user: "postgres"
  pass: "postgres"
  name: "postgres"

storage:
  path: "/app/uploads"

metrics:
  port: "9091"